# Generated by Django 5.2.15 on 2026-06-16 03:32

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CreditApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount_requested', models.DecimalField(decimal_places=2, max_digits=12)),
                ('purpose', models.TextField()),
                ('duration_months', models.PositiveIntegerField(default=6)),
                ('repayment_frequency', models.CharField(choices=[('weekly', 'Hebdomadaire'), ('monthly', 'Mensuel')], default='monthly', max_length=20)),
                ('status', models.CharField(choices=[('submitted', 'Soumise'), ('in_review', 'En analyse'), ('approved', 'Approuvée'), ('disbursed', 'Décaissée'), ('rejected', 'Rejetée')], default='submitted', max_length=20)),
                ('eligibility_score', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=5)),
                ('interest_rate', models.DecimalField(decimal_places=4, default=Decimal('0.1200'), max_digits=5)),
                ('region', models.CharField(blank=True, choices=[('abidjan', 'Abidjan'), ('bouake', 'Bouaké'), ('san_pedro', 'San-Pédro'), ('korhogo', 'Korhogo'), ('yamoussoukro', 'Yamoussoukro')], max_length=30)),
                ('rejection_reason', models.TextField(blank=True)),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('disbursed_at', models.DateTimeField(blank=True, null=True)),
                ('assigned_agent', models.ForeignKey(blank=True, limit_choices_to={'role__in': ['agent', 'admin']}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_credits', to=settings.AUTH_USER_MODEL)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='credit_applications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-submitted_at'],
            },
        ),
        migrations.CreateModel(
            name='CreditDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='credit_documents/')),
                ('document_type', models.CharField(max_length=100)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('credit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='credits.creditapplication')),
            ],
        ),
    ]
