# Generated by Django 5.2.15 on 2026-06-22 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='cni_number',
            field=models.CharField(blank=True, max_length=20, verbose_name='Numéro CNI'),
        ),
    ]
